### PR TITLE
Add example

### PR DESCRIPTION
**Pull request by jonaskello**

### CODE REVIEW

**Comment by AVGP** [comment]
Nice example! Thank you!

**Comment by jonaskello** [comment]
Thanks! I also involved my colleague @Jontem to do some updates according to the example SoftwareRenderer.js in the THREE repo.

Would it be possible to add me to npm also so I could publish a new version if needed?

**Comment by AVGP** [comment]
absolutely, what's your username on npm? jonaskello?

2016-11-17 15:14 GMT+01:00 Jonas Kello notifications@github.com:

**Comment by jonaskello** [comment]
Yes it's jonaskello there too. I saw you already added me, thanks :-).

**Pull request merged**
